
artifacts_root: [artifacts]

data_ingestion:
  root_dir: [artifacts/data_ingestion]
  source_URL: https://raw.githubusercontent.com/dushyantverma22/data_set/main/WineQT.csv
  local_data_file: artifacts/data_ingestion/WineQT.csv
  unzip_dir: artifacts/data_ingestion
