
artifacts_root: [artifacts]

data_ingestion:
  root_dir: [artifacts/data_ingestion]
  source_URL: https://raw.githubusercontent.com/dushyantverma22/data_set/main/WineQT.csv
  local_data_file: artifacts/data_ingestion/WineQT.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: [artifacts/data_validation]
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transforamtion
  data_path: artifacts/data_ingestion/WineQT.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_file_path: artifacts/data_transforamtion/train.csv
  test_file_path: artifacts/data_transforamtion/test.csv
  model_name: model.joblib